version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=T0r0m0ch02023
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
volumes:
  db:
    driver: local
